version: "3.7"
services:
    ams-app:
        build:
            args:
                user: 1000
                uid: 1000
            context: ./
            dockerfile: ./devops/conf/Dockerfile
        container_name: ams-app
        restart: on-failure
        working_dir: /var/www/
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - "PHP_IDE_CONFIG=serverName=ams-docker.local"
        volumes:
            - ./:/var/www
            - ./devops/php-ext/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./devops/php-ext/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./devops/conf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        networks:
            - ams
        depends_on:
            - ams-db
            # - pgsql
#            - ams-redis

    ams-db:
        image: mysql:latest
        container_name: ams-db
        restart: on-failure
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./devops/db:/var/lib/mysql
        networks:
            - ams
        security_opt:
            - seccomp:unconfined
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping" ]

    ams-nginx:
        image: nginx:latest
        container_name: ams-nginx
        restart: on-failure
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./devops/conf/nginx_default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - ams
        healthcheck:
            test: [ "CMD", "service", "nginx", "status"]

#    ams-redis:
#        image: 'redis:alpine'
#        container_name: ams-redis
#        #ports:
#        #    - '${FORWARD_REDIS_PORT:-6379}:6379'
#        volumes:
#            - './devops/redis:/data'
#        networks:
#            - ams
#        healthcheck:
#            test: ["CMD", "redis-cli", "ping"]
#
#    ams-memcached:
#        image: 'memcached:alpine'
#        container_name: ams-memcached
#        ports:
#            - '11211:11211'
#        networks:
#            - ams

#    mailhog:
#        image: 'mailhog/mailhog:latest'
#        ports:
#            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
#            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
#        networks:
#            - ams

networks:
    ams:
        driver: bridge

volumes:
    ams-db:
        driver: local
    ams-redis:
        driver: local
